require('config.gruvbox')
require('config.lualine')
require('config.nvim-tree')
require('config.nvim-treesitter')
require('config.comment')
require('config.iron')
require('config.nvim-surround')
require('config.leap')
